spring: 
  profiles:
    active: "prod"
  main:
    banner-mode: "off"

name: dev-YAML
environment: dev

firebase:
    name: don
    last-name: lok
    id: 12345


---
spring:
    profiles: test
name: test-YAML
environment: test
servers: 
    - www.abc.test.com
    - www.xyz.test.com
 
---
spring:
    profiles: prod
name: prod-YAML
environment: production
servers: 
    - www.abc.com
    - www.xyz.com